title = "Gitleaks Configuration"

[extend]
useDefault = true

[[rules]]
id = "fingerprint-api-key"
description = "Detected a possible Fingerprint API key, posing a risk of unauthorized use of subscription resources."
regex = '''(?i)([a-z0-9]{20})("|$)'''
secretGroup = 1
entropy = 3.5
keywords = [
    "key",
    "secret",
    "//",
    "/*",
]
[[rules.allowlists]]
paths = [ '''\.swift-format''' ]
